# .goreleaser.yml
version: 2
project_name: vlan-scout

env:
  - LIBS_DIR={{ .Env.PWD }}/.libs
  - NPCAP_DIR={{ .Env.PWD }}/.libs/npcap-sdk

before:
  hooks:
    - go mod tidy

builds:
  - id: vlan-scout-amd64
    main: .
    binary: vlan-scout
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu
      - CXX=zig c++ -target x86_64-linux-gnu
      - CGO_CFLAGS=-I{{ .Env.LIBS_DIR }}/libpcap-x86_64-linux-gnu
      - CGO_LDFLAGS=-L{{ .Env.LIBS_DIR }}/libpcap-x86_64-linux-gnu
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: vlan-scout-arm64
    main: .
    binary: vlan-scout
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-gnu
      - CXX=zig c++ -target aarch64-linux-gnu
      - CGO_CFLAGS=-I{{ .Env.LIBS_DIR }}/libpcap-aarch64-linux-gnu
      - CGO_LDFLAGS=-L{{ .Env.LIBS_DIR }}/libpcap-aarch64-linux-gnu
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: vlan-scout-windows
    main: .
    binary: vlan-scout
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows-gnu
      - CXX=zig c++ -target x86_64-windows-gnu
      - CGO_CFLAGS=-I{{ .Env.NPCAP_DIR }}/Include
      - CGO_LDFLAGS=-L{{ .Env.NPCAP_DIR }}/Lib/x64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

  # - id: vlan-scout-darwin-amd64
  #   main: .
  #   binary: vlan-scout
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=zig cc -target x86_64-macos
  #     - CXX=zig c++ -target x86_64-macos
  #     - CGO_CFLAGS=-I{{ .Env.LIBS_DIR }}/libpcap-x86_64-macos
  #     - CGO_LDFLAGS={{ .Env.LIBS_DIR }}/libpcap-x86_64-macos/libpcap.a
  #   flags:
  #     - -trimpath
  #   ldflags:
  #     - -s -w -X main.version={{.Version}} -extldflags=-static-libgcc

  # - id: vlan-scout-darwin-arm64
  #   main: .
  #   binary: vlan-scout
  #   goos:
  #     - darwin
  #   goarch:
  #     - arm64
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=zig cc -target aarch64-macos
  #     - CXX=zig c++ -target aarch64-macos
  #     - CGO_CFLAGS=-I{{ .Env.LIBS_DIR }}/libpcap-aarch64-macos
  #     - CGO_LDFLAGS={{ .Env.LIBS_DIR }}/libpcap-aarch64-macos/libpcap.a
  #   flags:
  #     - -trimpath
  #   ldflags:
  #     - -s -w -X main.version={{.Version}} -extldflags=-static-libgcc

  - id: vlan-scout-armhf
    main: .
    binary: vlan-scout
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target arm-linux-gnueabihf
      - CXX=zig c++ -target arm-linux-gnueabihf
      - CGO_CFLAGS=-I{{ .Env.LIBS_DIR }}/libpcap-arm-linux-gnueabihf
      - CGO_LDFLAGS=-L{{ .Env.LIBS_DIR }}/libpcap-arm-linux-gnueabihf
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: vlan-scout-arm64-musl
    main: .
    binary: vlan-scout-musl
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-musl
      - CXX=zig c++ -target aarch64-linux-musl
      - CGO_CFLAGS=-I{{ .Env.LIBS_DIR }}/libpcap-aarch64-linux-musl
      - CGO_LDFLAGS=-L{{ .Env.LIBS_DIR }}/libpcap-aarch64-linux-musl
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

nfpms:
  - id: vlan-scout
    # Package info
    maintainer: lanrat
    homepage: https://github.com/lanrat/vlan-scout
    description: |-
      network vlan enumeration tool
    # Supported formats
    formats:
      - deb
      - rpm
      - apk
      - archlinux

archives:
  - # Standard builds (excluding musl)
    id: standard
    ids:
      - vlan-scout-amd64
      - vlan-scout-arm64
      - vlan-scout-windows
      - vlan-scout-darwin-amd64
      - vlan-scout-darwin-arm64
      - vlan-scout-armhf
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: 
          - zip
  - # Musl build for OpenWRT
    id: musl
    ids:
      - vlan-scout-arm64-musl
    name_template: "{{ .ProjectName }}-musl_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'